package com.shinkarev.finalproject.command;

public class ParamName {

    private ParamName() {}

    public static final String LOGIN_ERROR = "loginError";
    public static final String PASSWORD_ERROR = "passwordError";
    public static final String EMAIL_ERROR = "emailError";
    public static final String NICKNAME_ERROR = "nicknameError";
    public static final String ERRORS_LIST = "errors";
    public static final String ERRORS_ON_ERROR_PAGE = "error";
    public static final String INSTRUMENT_NAME_ERROR = "instrumentNameError";
    public static final String INSTRUMENT_BRAND_ERROR = "instrumentBrandError";
    public static final String INSTRUMENT_COUNTRY_ERROR = "instrumentCountryError";
    public static final String INSTRUMENT_PRICE_ERROR = "instrumentPriceError";
    public static final String INSTRUMENT_DESCRIPTION_ERROR = "instrumentDescriptionError";
    public static final String INSTRUMENT_RATING_ERROR = "instrumentRatingError";
    public static final String INSTRUMENT_STATUS_ERROR = "instrumentStatusError";
    public static final String INSTRUMENT_TYPE_ERROR = "instrumentTypeError";
    public static final String MESSAGE_ERROR_LOGIN = "page.registration.login.message.error";
    public static final String MESSAGE_ERROR_EMAIL = "page.registration.email.message.error";
    public static final String COMMAND_PARAM = "command";
    public static final String LOCALIZATION = "localization";
    public static final String CONFIRM_KEY = "confirm";
    public static final String LOCALE = "locale";
    public static final String REFERER = "referer";
    public static final String METHOD_POST = "POST";
    public static final String RU_LOCALE = "ru-RU";
    public static final String EN_LOCALE = "en-US";
    public static final String REFERER_PARAM = "refererCommand";
    public static final String SUPPORTED_LOCALES = "supported.locales";
    public static final String REGISTRATION_VALUES = "registrationValues";
    public static final String ADMIN_PARAM_SEARCH_USER_BY_ID = "admin_search_by_id";
    public static final String USER = "user";
    public static final String USER_LIST_PARAM = "users";
    public static final String USER_ID_PARAM = "userId";
    public static final String COMMON_PROPERTIES = "common.properties";
    public static final String NEW_ROLE_PARAM = "new_role";
    public static final String NEW_STATUS_PARAM = "new_state";
    public static final String INSTRUMENT_TYPE = "instrument_type";
    public static final String INSTRUMENT_PARAM = "instrument";
    public static final String INSTRUMENT_DETAILS_ERROR = "instrument_error";
    public static final String PAGEABLE = "pageable";
    public static final String INSTRUMENTS = "instruments";
    public static final String INSTRUMENT_ID_PARAM = "instrumentId";
    public static final String INSTRUMENT_NEW_STATUS_PARAM = "new_status";
    public static final String ENTITY_NEW_TYPE_PARAM = "new_type";
    public static final String INSTRUMENTS_MESSAGE = "instrument_message";
    public static final String INSTRUMENT_TYPE_PARAM = "instrumentType";
    public static final String INSTRUMENT_STATUS_PARAM = "instrumentStatus";
    public static final String IMAGE_PARAM = "image";
    public static final String ADDRESS_DELIVERY = "address";
    public static final String RATING = "rating";
    public static final String RATING_MESSAGE = "message";
    public static final String ADMIN_PAGE_MESSAGE = "adminMessage";
    public static final String CART_ITEMS = "items";
    public static final String TOTAL_CART = "total";
    public static final String ITEM_QUANTITY = "quantity";
    public static final String PAYMENT = "payment";
    public static final String ORDERS_PARAM = "orders";
    public static final String ADMIN_MESSAGE = "message";
    public static final String PAGE_ERRORS_LOGIN_PASSWORD = "page.errors.login_password_error";
    public static final String PAGE_ERRORS_REGISTRATION_CONFIRMING = "page.errors.registration_confirming_error";
    public static final String EMPTY_INSTRUMENTS_LIST = "page.instruments.message";
    public static final String ORDER_DETAILS = "details";
    public static final String ORDER = "order";
    public static final String COLLECTIONS_PARAM = "items";
    public static final String ORDER_PARAM = "orderId";
    public static final String UPDATE_INSTRUMENT_PARAM = "updateValues";
    public static final String MARK = "mark";
    public static final String ERROR_CODE = "error_code";
    public static final String ERROR_NAME = "error_name";
    public static final Object SERVER_ERROR = "Server Error";
}
